import os
import json
import autogen
from dotenv import load_dotenv

parent_env_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env')
load_dotenv(parent_env_path)

def run_autogen_workflow(department: str, style: str, template: str, dimension: str, user_prompt: str, target_duration: int = 15) -> list:
    groq_api_key = os.getenv("GROQ_API_KEY")
    if not groq_api_key:
        raise ValueError("GROQ_API_KEY is not defined in the environment.")

    config_list = [{
        "model": "llama-3.3-70b-versatile",
        "api_key": groq_api_key,
        "base_url": "https://api.groq.com/openai/v1"
    }]

    llm_config = {
        "config_list": config_list,
        "temperature": 0.5,
        "response_format": {"type": "json_object"}
    }

    style_guide = ""
    if style.lower() == "cinematic":
        style_guide = "Use photorealistic cinematic terms: volumetric lighting, anamorphic lenses, depth of field, natural professional environments, realistic human presence."
    else:
        style_guide = "Use infographic and motion graphic terms: clean 2D vector illustrations, bold flat colors, kinetic typography, smooth isometric transitions, NO photorealism, isolated minimal backgrounds."

    num_scenes = max(1, target_duration // 5)
    
    system_message_director = f"""You are the Visual Director for a corporate video. 
Current Constraints:
- Department Topic: {department}
- System Prompt / Template Override: {template}
- Video Dimension: {dimension}
- Required Visual Style: {style.upper()}
- Visual Directives: {style_guide}
- Required Video Engine: Google Veo (Vertex AI)

Task: Take the User's core idea and write a structured list of scenes. 
- Each scene must be exactly 5 seconds long. Provide exactly {num_scenes} scenes (for a total of {target_duration} seconds).
- Each scene must have a `sceneNumber` (int), `description` (an engaging, user-facing story snippet explaining what is happening, e.g., "Our protagonist enters the office...", absolutely NO technical terms), and a `prompt` (the literal, hidden technical visual prompt that will be sent to the Google Veo generator).
- Make sure the visual `prompt` perfectly matches the Visual Directives mentioned above.
- CRITICAL: You must explicitly include any specific dates, numbers, or facts provided by the user in the final visual prompt.
- Output ONLY valid JSON containing an object with a single key "scenes" which holds the array of objects.
"""

    director = autogen.AssistantAgent(
        name="Director",
        system_message=system_message_director,
        llm_config=llm_config,
    )

    system_message_critic = f"""You are the Quality Critic. 
Your job is to review the Director's JSON output. 
- Ensure the JSON is an object with a "scenes" array.
- Ensure the visual constraints ({style_guide}) are strictly adhered to.
- Ensure all user-specified data (dates, names, facts) are preserved in the visual prompts.
- If it looks good, reply ONLY with the exact verbatim JSON object that the Director wrote, with NO conversational text. If it's flawed, instruct the Director to fix it."""

    critic = autogen.AssistantAgent(
        name="Critic",
        system_message=system_message_critic,
        llm_config=llm_config,
    )

    system_message_continuity = f"""You are the Continuity Expert.
Your job is to ensure that the scenes generated by the Director flow together seamlessly.
- Check that the main subjects (actors, environments) remain perfectly visually consistent across all {style.upper()} scenes.
- Ensure the lighting and mood are identical so that when stitched together, they look like one continuous video.
- Ensure the story snippets in `description` read like a cohesive narrative without exposing technical infra details.
- If there are continuity errors (e.g. Scene 1 has a man in a blue shirt, Scene 2 has him in a red shirt), instruct the Director to fix it.
- If it looks perfectly consistent, reply ONLY with the exact verbatim JSON object that the Director wrote, with NO conversational text.
"""

    continuity = autogen.AssistantAgent(
        name="ContinuityExpert",
        system_message=system_message_continuity,
        llm_config=llm_config,
    )

    user_proxy = autogen.UserProxyAgent(
        name="UserProxy",
        human_input_mode="NEVER",
        code_execution_config=False,
        max_consecutive_auto_reply=2,
        is_termination_msg=lambda x: "sceneNumber" in str(x.get("content", "")) and "scenes" in str(x.get("content", ""))
    )

    initial_message = f"Please draft the scenes for the following video concept: {user_prompt}"

    groupchat = autogen.GroupChat(
        agents=[user_proxy, director, critic, continuity],
        messages=[],
        max_round=6,
        allow_repeat_speaker=False
    )
    
    manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)

    user_proxy.initiate_chat(manager, message=initial_message)

    final_output = []
    for message in reversed(groupchat.messages):
        content = message.get("content", "")
        if "scenes" in content and "sceneNumber" in content:
            try:
                parsed = json.loads(content)
                if "scenes" in parsed:
                    final_output = parsed["scenes"]
                    break
            except Exception:
                # Fallback to loose extraction just in case
                import re
                match = re.search(r'\{.*"scenes"\s*:\s*\[.*\]\s*\}', content, re.DOTALL)
                if match:
                    try:
                        parsed = json.loads(match.group(0))
                        final_output = parsed.get("scenes", [])
                        break
                    except Exception:
                        pass

    if not final_output:
        print("Failed to extract JSON from conversation. Using blank fallback.")
        final_output = [{"sceneNumber": 1, "description": "Fallback scene", "prompt": f"A standard corporate video for {department}."}]

    return final_output

def run_autogen_blueprint(department: str, style: str, template: str, dimension: str, user_prompt: str) -> str:
    groq_api_key = os.getenv("GROQ_API_KEY")
    if not groq_api_key:
        raise ValueError("GROQ_API_KEY is not defined in the environment.")

    config_list = [{
        "model": "llama-3.3-70b-versatile",
        "api_key": groq_api_key,
        "base_url": "https://api.groq.com/openai/v1"
    }]

    llm_config = {
        "config_list": config_list,
        "temperature": 0.7,
    }

    system_message = f"""You are the Creative Director for a corporate video.
Current Constraints:
- Department Topic: {department}
- System Prompt / Template Override: {template}
- Video Dimension: {dimension}
- Required Visual Style: {style.upper()}

Task: Take the User's core idea and write a structured "Strategic Video Blueprint".
Format it strictly exactly like this (use markdown):

### Video Objective
(1-2 sentences on exactly what this video will accomplish)

### Key Content to Cover
- (Bullet point the specific details, user-provided data, rules, and facts mentioned in the prompt)
- (Ensure user-specific details are heavily emphasized here so the animation/scene backend won't miss them)

### Visual & Tonal Trajectory
(A paragraph describing the aesthetic, mood, lighting, and pacing based on the {style.upper()} style)

CRITICAL RULES:
- DO NOT write a scene-by-scene script or use words like "Scene 1". 
- Return ONLY the formatted markdown blueprint. No conversational filler or introductory text.
"""

    agent = autogen.AssistantAgent(
        name="CreativeDirector",
        system_message=system_message,
        llm_config=llm_config,
    )

    user_proxy = autogen.UserProxyAgent(
        name="UserProxy",
        human_input_mode="NEVER",
        code_execution_config=False,
        max_consecutive_auto_reply=0
    )

    initial_message = f"Please draft the strategic video blueprint for the following concept: {user_prompt}"

    res = user_proxy.initiate_chat(agent, message=initial_message)
    
    # Extract the last message from the agent
    final_text = "Video blueprint generation failed."
    for msg in reversed(user_proxy.chat_messages[agent]):
        if msg.get("role") == "assistant" or msg.get("name") == "CreativeDirector":
            final_text = msg.get("content", "").strip()
            break

    return final_text
